[package]
name = "mantra"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Mantra"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
specialfx = { git = "https://github.com/lloydeverett/specialfx", default-features = false }
tauri = { version = "2", features = [] }
